server:
  port: 8085

spring:
  application:
    name: aurora-inventory
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_ADDR:localhost:8848}

management:
  endpoints:
    web:
      exposure:
        include: health,info
