global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: skywalking-oap
    static_configs:
      - targets: ['skywalking-oap:1234']
