apiVersion: 1

contactPoints:
  - orgId: 1
    uid: local-webhook
    name: local-webhook
    receivers:
      - uid: local-webhook-receiver
        type: webhook
        disableResolveMessage: false
        settings:
          url: http://host.docker.internal:9977/grafana-alert
          httpMethod: POST
